# Generated by Django 3.2.2 on 2021-06-09 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210609_1102'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVModel',
        ),
    ]
